### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by cuthbe** [sevdokimov/log-viewer#152]
Trying tobuild locally, we are getting

Running com.logviewer.impl.LvHoconFilterSetProviderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.117 sec
Running com.logviewer.impl.LvPatternFormatRecognizerTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 sec
Running com.logviewer.filters.ThreadPredicateTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.175 sec
Running com.logviewer.filters.JsPredicateTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.431 sec <<< FAILURE!
test(com.logviewer.filters.JsPredicateTest)  Time elapsed: 0.431 sec  <<< ERROR!
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at com.logviewer.data2.BufferedFile.loadOnePage(BufferedFile.java:102)
	at com.logviewer.data2.BufferedFile.search(BufferedFile.java:47)
	at com.logviewer.data2.BufferedFile.loadLine(BufferedFile.java:373)
	at com.logviewer.data2.Log$LogSnapshot.processRecords(Log.java:419)
	at com.logviewer.data2.Snapshot.processRecords(Snapshot.java:15)
	at com.logviewer.filters.JsPredicateTest.before(JsPredicateTest.java:3

**Comment by sevdokimov** [comment]
Fixed.
