### ISSUE TITLE
1.0.8 Failed to read log

### ISSUE THREAD

**Issue by kknishev** [sevdokimov/log-viewer#210]
1.0.8 Failed to read log with the same config.conf from 1.0.7
```
Error details
×
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at com.logviewer.data2.BufferedFile.loadOnePage(BufferedFile.java:102)
	at com.logviewer.data2.BufferedFile.searchBack(BufferedFile.java:69)
	at com.logviewer.data2.BufferedFile.loadLine(BufferedFile.java:394)
	at com.logviewer.data2.Log$LogSnapshot.processRecordsBack(Log.java:400)
	at com.logviewer.web.session.LocalFileRecordLoader.lambda$start$0(LocalFileRecordLoader.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Error details
×
java.io.IOException: Disconnected
	at com.logviewer.data2.net.OutcomeConnection.onDisconnect(OutcomeConnection.java:112)
	at com.logviewer.data2.net.AbstractConnection.close(AbstractConnection.java:42)
	at com.logviewer.data2.net.AbstractConnection$1.completed(AbstractConnection.java:112)
	at com.logviewer.data2.net.AbstractConnection$1.completed(AbstractConnection.java:93)
	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.completed(Unknown Source)
	at sun.nio.ch.Iocp$EventHandlerTask.run(Unknown Source)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by sevdokimov** [comment]
Ops... I have build the release with Java 17 instead of Java 8. 
Fixed, 1.0.9 works fine with Java 8

**Comment by kknishev** [comment]
1.0.9 version still has an issue with log-paths from server (version is 1.0.6) - file opened, bur after ~1sec (or file refresh) show error:
```
java.io.IOException: Disconnected
	at com.logviewer.data2.net.OutcomeConnection.onDisconnect(OutcomeConnection.java:112)
	at com.logviewer.data2.net.AbstractConnection.close(AbstractConnection.java:42)
	at com.logviewer.data2.net.AbstractConnection$1.completed(AbstractConnection.java:99)
	at com.logviewer.data2.net.AbstractConnection$1.completed(AbstractConnection.java:93)
	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.completed(Unknown Source)
	at sun.nio.ch.Iocp$EventHandlerTask.run(Unknown Source)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
localy 1.0.9 working well

**Comment by sevdokimov** [comment]
Is there any error on another instance of log-viewer? Both instances are 1.0.9 ?

**Comment by kknishev** [comment]
> Both instances are 1.0.9

host 1.0.6, client 1.0.9

**Comment by sevdokimov** [comment]
You have to use 1.0.9 on all nodes. 
I should have increased the middle number in the version to let know about breaking changes. My fault.
